_wandb:
    value:
        cli_version: 0.25.0
        e:
            oq415h2wlp2fx1z6vdi6zfoz80b8w0p9:
                apple:
                    ecpuCores: 4
                    gpuCores: 32
                    memoryGb: 36
                    name: Apple M4 Max
                    pcpuCores: 10
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "2147483648"
                codePath: run_training.py
                codePathLocal: run_training.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "391943294976"
                email: noahn@stanford.edu
                executable: /opt/homebrew/opt/python@3.14/bin/python3.14
                git:
                    commit: caca95231bee831c2c3390a421a80bdadeb164ea
                    remote: https://github.com/doubleMcyber/LXP
                host: DN0a1f2252.SUNet
                memory:
                    total: "38654705664"
                os: macOS-15.1-arm64-arm-64bit-Mach-O
                program: /Users/noahnowaczewski/LXP/run_training.py
                python: CPython 3.14.2
                root: /Users/noahnowaczewski/LXP
                startedAt: "2026-03-05T01:40:26.764385Z"
                writerId: oq415h2wlp2fx1z6vdi6zfoz80b8w0p9
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 53
                - 71
            "3":
                - 2
                - 16
                - 61
            "4": 3.14.2
            "5": 0.25.0
            "6": 5.3.0
            "12": 0.25.0
            "13": darwin-arm64
compressed_steps:
    value: 16
eps:
    value: 1e-08
lambda_geom:
    value: 1
lambda_pref:
    value: 1
lambda_task:
    value: 1
learning_rate:
    value: 1e-05
max_grad_norm:
    value: 1
num_epochs:
    value: 1
wandb_enabled:
    value: true
wandb_entity:
    value: null
wandb_project:
    value: lxp-stage2
weight_decay:
    value: 0.01
